### ISSUE TITLE
Kansas City eventbrite link inactive

### ISSUE THREAD

**Issue by emeth-** [c4tk/c4tk#2]
Hey Chris,

I'm a Saint Louis guy, looking to drive to the Kansas City c4tk event.

I note that the eventbrite link here isn't active:
https://github.com/chrislim/c4tk/blob/gh-pages/kansascity2015G.html#L369

Any news on that? Has the Kansas City event been canceled (or just not setup yet?). Any thoughts about getting something rolling in Saint Louis?

**Comment by emeth-** [comment]
I just received an email back from Linda Fields, one of the organizers for the Kansas City event, that it was indeed canceled. That clears that up - it just hasn't been removed from the website yet.

**Comment by chrisarmas** [comment]
Emeth
You are looking at the code in GitHub and not the live
http://codeforthekingdom.org
The event has been previously removed from the live website. Would you be
able to go to another city?
Let's chat after the global hackathon about a possible 2016 St Louis one.
Thanks
Chris

**Comment by emeth-** [comment]
Actually I found it on the live website via a google search first, then came here to try to figure out what's up.

http://codeforthekingdom.org/kansascity2015G.html

Sounds good. I'm friends with some people going to the Los Angeles event, so I'll Google Hangout in with them and work with them. Thanks for setting up this event!

**Comment by chrisarmas** [comment]
Great!!! Let me know how it works for you doing the remote participation.
Then let's talk about St Louis. Looking forward to it.
